name: deploy-frontend
on:
  push:
    branches:
      -master
jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Installing Node.js
        uses: actions/setup-node@v3
        with: 
          node-version: "18"
      - name: Installing Dependencies
        run: npm install
      - name: Build
        run: npm run build